#!/bin/sh

echo ""
echo "Checkm4te! ♕"
echo ""
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo ""
echo "Thank You For Installing Violet v1.1.1"
echo ""
echo "Created by AppleWorm ♤"
