BUNDLE_NAME = VioletPreferences

VioletPreferences_FILES = $(wildcard *.m)
VioletPreferences_FRAMEWORKS = UIKit
VioletPreferences_PRIVATE_FRAMEWORKS = Preferences
VioletPreferences_INSTALL_PATH = /Library/PreferenceBundles
VioletPreferences_CFLAGS = -fobjc-arc
VioletPreferences_EXTRA_FRAMEWORKS = Cephei CepheiPrefs
VioletPreferences_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
